Updating perfusion derivatives documentation
CBICA/CaPTk pull request #1324
Opened 2020-09-25 18:41 UTC by ashishsingh18

Fix #1323

2020-09-25 19:28 UTC, sarthakpati requested changes

2020-09-25 19:28 UTC, sarthakpati commented on src/view/gui/fMainWindow.cpp
> +    //perfalignPanel.exec();
Revert these changes, please.

2020-09-28 00:37 UTC, AlexanderGetka-cbica approved these changes
Looks good now.

2020-09-28 10:33 UTC, sarthakpati approved these changes

2020-09-28 10:33 UTC, merged