1369
CBICA/CaPTk pull request #1372
Opened 2020-11-11 16:47 UTC by sarthakpati

Fixes issue #1369

## Proposed Changes
  - perfusion alignment plots are getting saved

2020-11-12 17:06 UTC, ashishsingh18 requested changes
Looks great. Just a minor change - Can we move the function to cpp file?

2020-11-12 18:44 UTC, sarthakpati commented
> Looks great. Just a minor change - Can we move the function to cpp file?

I was initially trying to use the implementation that you had (basically, the function in CPP). But, the standalone applications were not getting linked properly and I unfortunately don't have time to debug this. Please feel free to have a crack it if you want but if you don't have the time either, I would suggest please merge.

2020-11-12 23:01 UTC, ashishsingh18 commented
> 
> 
> > Looks great. Just a minor change - Can we move the function to cpp file?
> 
> I was initially trying to use the implementation that you had (basically, the function in CPP). But, the standalone applications were not getting linked properly and I unfortunately don't have time to debug this. Please feel free to have a crack it if you want but if you don't have the time either, I would suggest please merge.

This is very simple. Just move the implementation to cpp file. I fixed it and created a [PR](https://github.com/sarthakpati/CaPTk/pull/64) to your branch.

2020-11-12 23:07 UTC, sarthakpati commented
> > > Looks great. Just a minor change - Can we move the function to cpp file?
> > 
> > 
> > I was initially trying to use the implementation that you had (basically, the function in CPP). But, the standalone applications were not getting linked properly and I unfortunately don't have time to debug this. Please feel free to have a crack it if you want but if you don't have the time either, I would suggest please merge.
> 
> This is very simple. Just move the implementation to cpp file. I fixed it and created a [PR](https://github.com/sarthakpati/CaPTk/pull/64) to your branch.

Ashish, I _know_ how to move something to the CPP file. The issue is that it causes link errors.

2020-11-12 23:16 UTC, ashishsingh18 commented
> 
> 
> > > > Looks great. Just a minor change - Can we move the function to cpp file?
> > > 
> > > 
> > > I was initially trying to use the implementation that you had (basically, the function in CPP). But, the standalone applications were not getting linked properly and I unfortunately don't have time to debug this. Please feel free to have a crack it if you want but if you don't have the time either, I would suggest please merge.
> > 
> > 
> > This is very simple. Just move the implementation to cpp file. I fixed it and created a [PR](https://github.com/sarthakpati/CaPTk/pull/64) to your branch.
> 
> Ashish, I _know_ how to move something to the CPP file. The issue is that it causes link errors.

I am not getting any linker errors after moving to cpp.

2020-11-12 23:17 UTC, sarthakpati commented
> > > > > Looks great. Just a minor change - Can we move the function to cpp file?
> > > > 
> > > > 
> > > > I was initially trying to use the implementation that you had (basically, the function in CPP). But, the standalone applications were not getting linked properly and I unfortunately don't have time to debug this. Please feel free to have a crack it if you want but if you don't have the time either, I would suggest please merge.
> > > 
> > > 
> > > This is very simple. Just move the implementation to cpp file. I fixed it and created a [PR](https://github.com/sarthakpati/CaPTk/pull/64) to your branch.
> > 
> > 
> > Ashish, I _know_ how to move something to the CPP file. The issue is that it causes link errors.
> 
> I am not getting any linker errors after moving to cpp.

Great! Have you merged from this change that I am proposing? That is, are you actually _using_ that function?

2020-11-12 23:18 UTC, ashishsingh18 commented
> 
> 
> > > > > > Looks great. Just a minor change - Can we move the function to cpp file?
> > > > > 
> > > > > 
> > > > > I was initially trying to use the implementation that you had (basically, the function in CPP). But, the standalone applications were not getting linked properly and I unfortunately don't have time to debug this. Please feel free to have a crack it if you want but if you don't have the time either, I would suggest please merge.
> > > > 
> > > > 
> > > > This is very simple. Just move the implementation to cpp file. I fixed it and created a [PR](https://github.com/sarthakpati/CaPTk/pull/64) to your branch.
> > > 
> > > 
> > > Ashish, I _know_ how to move something to the CPP file. The issue is that it causes link errors.
> > 
> > 
> > I am not getting any linker errors after moving to cpp.
> 
> Great! Have you merged from this change that I am proposing? That is, are you actually _using_ that function?

Have you tried the changes I proposed and created the PR? I opened that PR only after testing it. That works!

2020-11-12 23:22 UTC, sarthakpati commented
> > > > > > > Looks great. Just a minor change - Can we move the function to cpp file?
> > > > > > 
> > > > > > 
> > > > > > I was initially trying to use the implementation that you had (basically, the function in CPP). But, the standalone applications were not getting linked properly and I unfortunately don't have time to debug this. Please feel free to have a crack it if you want but if you don't have the time either, I would suggest please merge.
> > > > > 
> > > > > 
> > > > > This is very simple. Just move the implementation to cpp file. I fixed it and created a [PR](https://github.com/sarthakpati/CaPTk/pull/64) to your branch.
> > > > 
> > > > 
> > > > Ashish, I _know_ how to move something to the CPP file. The issue is that it causes link errors.
> > > 
> > > 
> > > I am not getting any linker errors after moving to cpp.
> > 
> > 
> > Great! Have you merged from this change that I am proposing? That is, are you actually _using_ that function?
> 
> Have you tried the changes I proposed and created the PR? I opened that PR only after testing it. That works!

I just said that it _does not_ work. Here is a screenshot:
![image](https://user-images.githubusercontent.com/11719673/99008394-0f3a8880-2514-11eb-9b95-9f8324bf31e0.png)

2020-11-12 23:29 UTC, AlexanderGetka-cbica commented
If you're adding the cpp file maybe it just needs a cmake configure to pick it up? If the Azure build succeeds, we'll know it links.

2020-11-12 23:30 UTC, ashishsingh18 commented
> 
> 
> > > > > > > > Looks great. Just a minor change - Can we move the function to cpp file?
> > > > > > > 
> > > > > > > 
> > > > > > > I was initially trying to use the implementation that you had (basically, the function in CPP). But, the standalone applications were not getting linked properly and I unfortunately don't have time to debug this. Please feel free to have a crack it if you want but if you don't have the time either, I would suggest please merge.
> > > > > > 
> > > > > > 
> > > > > > This is very simple. Just move the implementation to cpp file. I fixed it and created a [PR](https://github.com/sarthakpati/CaPTk/pull/64) to your branch.
> > > > > 
> > > > > 
> > > > > Ashish, I _know_ how to move something to the CPP file. The issue is that it causes link errors.
> > > > 
> > > > 
> > > > I am not getting any linker errors after moving to cpp.
> > > 
> > > 
> > > Great! Have you merged from this change that I am proposing? That is, are you actually _using_ that function?
> > 
> > 
> > Have you tried the changes I proposed and created the PR? I opened that PR only after testing it. That works!
> 
> I just said that it _does not_ work. Here is a screenshot:
> ![image](https://user-images.githubusercontent.com/11719673/99008394-0f3a8880-2514-11eb-9b95-9f8324bf31e0.png)

It works perfectly on my side. 
![image](https://user-images.githubusercontent.com/43445206/99008865-04ccbe80-2515-11eb-8c14-a6733e6c7759.png)

Why don't you let it run on Azure?

2020-11-12 23:30 UTC, sarthakpati commented
> If you're adding the cpp file maybe it just needs a cmake configure to pick it up? If the Azure build succeeds, we'll know it links.

Well, it flunked out on my local machine. If I know something fails locally, I am obviously not going to ask Azure to go through it.

2020-11-12 23:31 UTC, sarthakpati commented
> > > > > > > > > Looks great. Just a minor change - Can we move the function to cpp file?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I was initially trying to use the implementation that you had (basically, the function in CPP). But, the standalone applications were not getting linked properly and I unfortunately don't have time to debug this. Please feel free to have a crack it if you want but if you don't have the time either, I would suggest please merge.
> > > > > > > 
> > > > > > > 
> > > > > > > This is very simple. Just move the implementation to cpp file. I fixed it and created a [PR](https://github.com/sarthakpati/CaPTk/pull/64) to your branch.
> > > > > > 
> > > > > > 
> > > > > > Ashish, I _know_ how to move something to the CPP file. The issue is that it causes link errors.
> > > > > 
> > > > > 
> > > > > I am not getting any linker errors after moving to cpp.
> > > > 
> > > > 
> > > > Great! Have you merged from this change that I am proposing? That is, are you actually _using_ that function?
> > > 
> > > 
> > > Have you tried the changes I proposed and created the PR? I opened that PR only after testing it. That works!
> > 
> > 
> > I just said that it _does not_ work. Here is a screenshot:
> > ![image](https://user-images.githubusercontent.com/11719673/99008394-0f3a8880-2514-11eb-9b95-9f8324bf31e0.png)
> 
> It works perfectly on my side.
> ![image](https://user-images.githubusercontent.com/43445206/99008865-04ccbe80-2515-11eb-8c14-a6733e6c7759.png)
> 
> Why don't you let it run on Azure?

Great, then why don't you put it as a separate PR and I can close this? I don't want to take responsibility for that code, at all.

2020-11-12 23:45 UTC, ashishsingh18 commented
> 
> 
> > > > > > > > > > Looks great. Just a minor change - Can we move the function to cpp file?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > I was initially trying to use the implementation that you had (basically, the function in CPP). But, the standalone applications were not getting linked properly and I unfortunately don't have time to debug this. Please feel free to have a crack it if you want but if you don't have the time either, I would suggest please merge.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > This is very simple. Just move the implementation to cpp file. I fixed it and created a [PR](https://github.com/sarthakpati/CaPTk/pull/64) to your branch.
> > > > > > > 
> > > > > > > 
> > > > > > > Ashish, I _know_ how to move something to the CPP file. The issue is that it causes link errors.
> > > > > > 
> > > > > > 
> > > > > > I am not getting any linker errors after moving to cpp.
> > > > > 
> > > > > 
> > > > > Great! Have you merged from this change that I am proposing? That is, are you actually _using_ that function?
> > > > 
> > > > 
> > > > Have you tried the changes I proposed and created the PR? I opened that PR only after testing it. That works!
> > > 
> > > 
> > > I just said that it _does not_ work. Here is a screenshot:
> > > ![image](https://user-images.githubusercontent.com/11719673/99008394-0f3a8880-2514-11eb-9b95-9f8324bf31e0.png)
> > 
> > 
> > It works perfectly on my side.
> > ![image](https://user-images.githubusercontent.com/43445206/99008865-04ccbe80-2515-11eb-8c14-a6733e6c7759.png)
> > Why don't you let it run on Azure?
> 
> Great, then why don't you put it as a separate PR and I can close this? I don't want to take responsibility for that code, at all.

It really  should go with this PR. I don't understand the responsibility part. This is your code. I just moved it to the cpp file verbatim.

2020-11-12 23:47 UTC, sarthakpati commented
> It really should go with this PR. I don't understand the responsibility part. This is your code. I just moved it to the cpp file verbatim.

The point is that it does not work for me. If I cannot generate results with it, I am not going to take responsibility for it.

2020-11-16 15:08 UTC, ashishsingh18 approved these changes

2020-12-03 20:55 UTC, AlexanderGetka-cbica approved these changes
Approving based on prior discussion. Adding an enhancement request to change the .cpp/.h divide later once we have more time to double-check.

2020-12-03 22:03 UTC, merged