Perfusion-related fixes (PHI, PerfusionPCA, GUI/CLI)
CBICA/CaPTk pull request #1476
Opened 2022-02-23 14:41 UTC by AlexanderGetka-cbica

Fixed #1472 
Fixed #1473 
Fixed #1474 
Fixed #1475
Seems to have also fixed #1450 

Summary:
Adds a text indicator of 4D slice number to the slider bar.
Clarifies perfusionPCA filename requirements (but doesn't make them more intelligent).
Fixes loading of 4D and 3D images together.
Adds batch mode and time-points parameters to PHI (EGFRvIIISurrogateIndex).

Also disables self-host mac builds in the Azure pipeline. @sarthakpati may need to configure the requirements on GitHub side, not sure about that.

2022-03-10 20:22 UTC, sarthakpati commented
Are we trying to fix Codacy issues, as well? For e.g.:

![image](https://user-images.githubusercontent.com/11719673/157748159-3fc22c16-bd9d-4068-a41e-bcc5c33c4027.png)

2022-03-11 03:51 UTC, AlexanderGetka-cbica commented
> Are we trying to fix Codacy issues, as well? For e.g.:
> 
> ![image](https://user-images.githubusercontent.com/11719673/157748159-3fc22c16-bd9d-4068-a41e-bcc5c33c4027.png)

Ah, yeah -- I should've caught that. My bad. I won't change the code-style related ones for this but I'll address any "medium" or above.

2022-03-11 17:30 UTC, sarthakpati approved these changes
~LGTM!~

Accidentally put this on.

2022-03-11 17:31 UTC, merged

2022-03-11 17:32 UTC, sarthakpati requested changes

2022-03-11 17:32 UTC, sarthakpati commented on src/view/gui/fMainWindow.cpp
> +      //imagePerf = ChangeImageDirectionToIdentity< ImageTypeFloat4D >(tempImage.second);
Any reason for this commented code to be present? If yes, then please place a comment here.

2022-03-11 17:34 UTC, AlexanderGetka-cbica commented
I'll remove that commented code in the PR that updates the docs and version. Thanks @sarthakpati !